services:

  node:
    build:
      context: .
      dockerfile: ./docker/NODE.ps.dockerfile
    env_file:
      - .env
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    volumes:
      - ./services/ts/src:/app/src
      - /app/node_modules
    networks:
      - ps-network

  db:
    build:
      context: .
      dockerfile: ./docker/POSTGRES.ps.dockerfile
    container_name: ${POSTGRES_SERVER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/db/scripts/init/dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar
      - ./data/db/scripts/init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - ps-network

volumes:
  postgres-data:

networks:
  ps-network: